openapi: 3.1.0
info:
  title: Astro Weekday API (Verified Astro Version)
  version: "2.4.0"
  description: |
    API สำหรับตรวจสอบวันจริง, คำนวณพื้นดวง / ดาวจร / ดวงคู่
    พร้อมระบบยืนยันความถูกต้องของวัน (Pre-Validation + Verified Layer)
    รองรับทุก timezone และป้องกันความสับสน พ.ศ./ค.ศ.

servers:
  - url: https://astro-weekday-pro-auto.vercel.app

paths:
  /api/validate-weekday:
    get:
      operationId: validateWeekday
      summary: ตรวจสอบวันจริงก่อนใช้ในการทำนาย (Pre-Validation Layer)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "03/10/2568"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: boolean
                  verified_text:
                    type: string
                  weekday_full:
                    type: string
                  thai_date_long:
                    type: string

  /api/weekday:
    get:
      operationId: getWeekday
      summary: ตรวจสอบวันจริงจากวันที่ (พร้อมตรวจสอบความถูกต้อง)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "03/10/2568"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  date: {type: string}
                  timezone: {type: string}
                  weekday: {type: string}
                  calendar: {type: string}
                  year_be: {type: integer}
                  year_ce: {type: integer}
                  verified: {type: boolean}
                  verified_text: {type: string}

  /api/weekday-th:
    get:
      operationId: getWeekdayThai
      summary: แปลงวันที่ไทยและแสดงวันจริง (พร้อมตรายืนยันความถูกต้อง)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "03/10/2568"
        - name: style
          in: query
          required: false
          schema:
            type: string
            enum: ["short", "long"]
            default: "short"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  thai_date_long: {type: string}
                  weekday_full: {type: string}
                  verified: {type: boolean}
                  verified_text: {type: string}

  /api/astro-weekday:
    get:
      operationId: getAstroWeekday
      summary: ตรวจสอบวันจริง + เวลา + timezone + สถานที่เกิด (พร้อมยืนยันวันจริง)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time
          in: query
          required: false
          schema:
            type: string
            example: "11:00"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
        - name: place
          in: query
          required: false
          schema:
            type: string
            example: "Bangkok"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  weekday: {type: string}
                  verified: {type: boolean}
                  verified_text: {type: string}
                  local_datetime: {type: string}
                  utc_datetime: {type: string}

  /api/astro-chart:
    get:
      operationId: getAstroChart
      summary: คำนวณพื้นดวง (เลือก sidereal/tropical อัตโนมัติ และตรวจวันจริง)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time
          in: query
          required: true
          schema:
            type: string
            example: "11:00"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
        - name: lat
          in: query
          required: false
          schema:
            type: number
            example: 13.75
        - name: lon
          in: query
          required: false
          schema:
            type: number
            example: 100.5
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  planets: {type: object}
                  verified: {type: boolean}
                  verified_text: {type: string}

  /api/astro-transit:
    get:
      operationId: getAstroTransit
      summary: วิเคราะห์ดาวจรเทียบพื้นดวง
      parameters:
        - name: base_date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: base_time
          in: query
          required: false
          schema:
            type: string
            example: "12:00"
        - name: target_date
          in: query
          required: false
          schema:
            type: string
            example: "08/05/2569"
        - name: lat
          in: query
          required: false
          schema:
            type: number
            example: 13.75
        - name: lon
          in: query
          required: false
          schema:
            type: number
            example: 100.5
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response

  /api/astro-match:
    get:
      operationId: getAstroMatch
      summary: วิเคราะห์ดวงคู่ (ความสัมพันธ์)
      parameters:
        - name: date1
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time1
          in: query
          required: true
          schema:
            type: string
            example: "11:00"
        - name: lat1
          in: query
          required: true
          schema:
            type: number
            example: 13.75
        - name: lon1
          in: query
          required: true
          schema:
            type: number
            example: 100.5
        - name: date2
          in: query
          required: true
          schema:
            type: string
            example: "08/06/2514"
        - name: time2
          in: query
          required: true
          schema:
            type: string
            example: "23:56"
        - name: lat2
          in: query
          required: true
          schema:
            type: number
            example: 18.79
        - name: lon2
          in: query
          required: true
          schema:
            type: number
            example: 98.98
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
