openapi: 3.1.0
info:
  title: Astro Weekday API
  version: "1.0.1"
  description: API สำหรับตรวจสอบวันจริงและคำนวณดวงพื้นดวง

servers:
  - url: https://astro-weekday-pro-auto.vercel.app

paths:
  /api/weekday:
    get:
      operationId: getWeekday
      summary: ตรวจสอบวันจริงจากวันที่
      parameters:
        - name: date
          in: query
          required: true
          schema: { type: string, example: "08/05/2569" }
      responses:
        "200":
          description: Successful Response

  /api/weekday-th:
    get:
      operationId: getThaiDate
      summary: คืนข้อความวันที่ไทยสำเร็จรูป (ตรวจวันจริง + แปลง พ.ศ.)
      parameters:
        - name: date
          in: query
          required: true
          schema: { type: string, example: "08/05/2569" }
        - name: style
          in: query
          required: false
          schema:
            type: string
            enum: ["short","long"]
            default: "short"
      responses:
        "200":
          description: Successful Response

  /api/astro-chart:
    get:
      operationId: getAstroChart
      summary: คำนวณดวงดาวพื้นดวง (จำลอง)
      parameters:
        - name: date
          in: query
          required: true
          schema: { type: string, example: "24/11/2514" }
        - name: time
          in: query
          required: true
          schema: { type: string, example: "11:00" }
        - name: lat
          in: query
          schema: { type: number, example: 13.75 }
        - name: lon
          in: query
          schema: { type: number, example: 100.5 }
      responses:
        "200":
          description: Successful Response
