openapi: 3.1.0
info:
  title: Astro Weekday API (v2.6.0 – Auto Validation Middleware)
  version: "2.6.0"
  description: |
    API สำหรับตรวจสอบวันจริง, คำนวณพื้นดวง / ดาวจร / ดวงคู่
    พร้อมระบบ Auto Validation ที่ตรวจสอบวันจริงอัตโนมัติทุกครั้ง
    รองรับทุก format วันที่ (DD/MM/YYYY, YYYY-MM-DD, 27-10-68 ฯลฯ)
    ป้องกันความสับสนระหว่าง พ.ศ. และ ค.ศ. และรองรับ timezone ทั่วโลก

servers:
  - url: https://astro-weekday-pro-auto.vercel.app

paths:
  /api/validate-weekday:
    get:
      operationId: validateWeekday
      summary: ตรวจสอบวันจริงก่อนใช้ในการทำนาย (Pre-Validation Layer)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "2025-10-27"
          description: วันที่รูปแบบใดก็ได้ (DD/MM/YYYY, YYYY-MM-DD, 27-10-68)
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: boolean
                    example: true
                  verified_text:
                    type: string
                    example: "✅ ตรวจสอบแล้ว: วันจันทร์ที่ 27 ตุลาคม 2568 (ตรงตามปฏิทินจริง)"
                  weekday_full:
                    type: string
                    example: "จันทร์"
                  thai_date_long:
                    type: string
                    example: "วันจันทร์ที่ 27 ตุลาคม 2568 (ค.ศ. 2025)"

  /api/weekday:
    get:
      operationId: getWeekday
      summary: ตรวจสอบวันจริงจากวันที่ (รองรับทุก format + Auto Validation)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "27/10/2568"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  date: {type: string, example: "27/10/2568"}
                  timezone: {type: string, example: "Asia/Bangkok"}
                  weekday: {type: string, example: "จันทร์"}
                  calendar: {type: string, example: "BE"}
                  year_be: {type: integer, example: 2568}
                  year_ce: {type: integer, example: 2025}
                  verified: {type: boolean, example: true}
                  verified_text: {type: string, example: "✅ ตรวจสอบแล้ว: วันจันทร์ที่ 27 ตุลาคม 2568 (ตรงตามปฏิทินจริง)"}

  /api/weekday-th:
    get:
      operationId: getWeekdayThai
      summary: แปลงวันที่ไทยและแสดงวันจริง (พร้อม Auto Validation)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "27-10-68"
        - name: style
          in: query
          required: false
          schema:
            type: string
            enum: ["short", "long"]
            default: "short"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  thai_date_long: {type: string, example: "วันจันทร์ที่ 27 ตุลาคม 2568 (ค.ศ. 2025)"}
                  weekday_full: {type: string, example: "จันทร์"}
                  verified: {type: boolean, example: true}
                  verified_text: {type: string, example: "✅ ตรวจสอบแล้ว: วันจันทร์ที่ 27 ตุลาคม 2568 (ตรงตามปฏิทินจริง)"}

  /api/astro-weekday:
    get:
      operationId: getAstroWeekday
      summary: ตรวจสอบวันจริง + เวลา + timezone + สถานที่เกิด (พร้อม Auto Validation)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "2025-10-27"
        - name: time
          in: query
          required: false
          schema:
            type: string
            example: "11:00"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
        - name: place
          in: query
          required: false
          schema:
            type: string
            example: "Bangkok"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  weekday: {type: string, example: "จันทร์"}
                  verified: {type: boolean, example: true}
                  verified_text: {type: string, example: "✅ ตรวจสอบแล้ว: วันจันทร์ที่ 27 ตุลาคม 2568 (ตรงตามปฏิทินจริง)"}
                  local_datetime: {type: string, example: "2025-10-27T11:00:00+07:00"}
                  utc_datetime: {type: string, example: "2025-10-27T04:00:00+00:00"}

  /api/astro-chart:
    get:
      operationId: getAstroChart
      summary: คำนวณพื้นดวง (เลือก sidereal/tropical อัตโนมัติ + Auto Validation)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time
          in: query
          required: true
          schema:
            type: string
            example: "11:00"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
        - name: lat
          in: query
          required: false
          schema:
            type: number
            example: 13.75
        - name: lon
          in: query
          required: false
          schema:
            type: number
            example: 100.5
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified: {type: boolean, example: true}
                  verified_text: {type: string, example: "✅ ตรวจสอบแล้ว: วันพุธที่ 24 พฤศจิกายน 2514 (ตรงตามปฏิทินจริง)"}
                  planets: {type: object}

  /api/astro-transit:
    get:
      operationId: getAstroTransit
      summary: วิเคราะห์ดาวจรเทียบพื้นดวง
      parameters:
        - name: base_date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: base_time
          in: query
          required: false
          schema:
            type: string
            example: "12:00"
        - name: target_date
          in: query
          required: false
          schema:
            type: string
            example: "08/05/2569"
        - name: lat
          in: query
          required: false
          schema:
            type: number
            example: 13.75
        - name: lon
          in: query
          required: false
          schema:
            type: number
            example: 100.5
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response

  /api/astro-match:
    get:
      operationId: getAstroMatch
      summary: วิเคราะห์ดวงคู่ (ความสัมพันธ์)
      parameters:
        - name: date1
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time1
          in: query
          required: true
          schema:
            type: string
            example: "11:00"
        - name: lat1
          in: query
          required: true
          schema:
            type: number
            example: 13.75
        - name: lon1
          in: query
          required: true
          schema:
            type: number
            example: 100.5
        - name: date2
          in: query
          required: true
          schema:
            type: string
            example: "08/06/2514"
        - name: time2
          in: query
          required: true
          schema:
            type: string
            example: "23:56"
        - name: lat2
          in: query
          required: true
          schema:
            type: number
            example: 18.79
        - name: lon2
          in: query
          required: true
          schema:
            type: number
            example: 98.98
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
