openapi: 3.1.0
info:
  title: Astro Weekday API
  version: "1.0.0"
  description: API สำหรับตรวจสอบวันจริงและคำนวณดวงพื้นดวง ดาวจร และดวงคู่

servers:
  - url: https://astro-weekday-pro-auto.vercel.app   # ✅ URL จริงบน Vercel

paths:
  /api/weekday:
    get:
      operationId: getWeekday
      summary: ตรวจสอบวันจริงจากวันที่
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "10/09/2568"
          description: วันที่รูปแบบ DD/MM/YYYY (พ.ศ. หรือ ค.ศ.)
      responses:
        "200":
          description: Successful Response

  /api/astro-chart:
    get:
      operationId: getAstroChart
      summary: คำนวณดวงดาวพื้นดวง
      parameters:
        - name: date
          in: query
          required: true
          schema: { type: string, example: "24/11/2514" }
        - name: time
          in: query
          required: true
          schema: { type: string, example: "11:00" }
        - name: timezone
          in: query
          schema: { type: string, example: "Asia/Bangkok" }
        - name: lat
          in: query
          schema: { type: number, example: 13.75 }
        - name: lon
          in: query
          schema: { type: number, example: 100.5 }
      responses:
        "200":
          description: ตำแหน่งดาวและราศี

  /api/astro-transit:
    get:
      operationId: getAstroTransit
      summary: ดูตำแหน่งดาวจร (Transit)
      parameters:
        - name: base_date
          in: query
          required: true
          schema: { type: string, example: "24/11/2514" }
        - name: base_time
          in: query
          schema: { type: string, example: "11:00" }
        - name: target_date
          in: query
          schema: { type: string, example: "10/10/2568" }
        - name: lat
          in: query
          schema: { type: number, example: 13.75 }
        - name: lon
          in: query
          schema: { type: number, example: 100.5 }
      responses:
        "200":
          description: ดาวจรและการวิเคราะห์

  /api/astro-match:
    get:
      operationId: getAstroMatch
      summary: วิเคราะห์ดวงคู่ (คู่รักหรือหุ้นส่วน)
      parameters:
        - name: date1
          in: query
          required: true
          schema: { type: string, example: "24/11/2514" }
        - name: time1
          in: query
          required: true
          schema: { type: string, example: "11:00" }
        - name: lat1
          in: query
          schema: { type: number, example: 13.75 }
        - name: lon1
          in: query
          schema: { type: number, example: 100.5 }
        - name: date2
          in: query
          required: true
          schema: { type: string, example: "8/6/2514" }
        - name: time2
          in: query
          required: true
          schema: { type: string, example: "23:56" }
        - name: lat2
          in: query
          schema: { type: number, example: 18.79 }
        - name: lon2
          in: query
          schema: { type: number, example: 98.98 }
      responses:
        "200":
          description: วิเคราะห์ความสัมพันธ์ดวงคู่
