openapi: 3.1.0
info:
  title: Astro Weekday API (Timezone Aware)
  version: "2.2.0"
  description: |
    API สำหรับตรวจสอบวันจริง และคำนวณพื้นดวง / ดาวจร / ดวงคู่
    รองรับทั้งระบบราศีสากล (Tropical) และนิรายนะ (Sidereal)
    โดยเลือกอัตโนมัติจากประเทศหรือ timezone

servers:
  - url: https://astro-weekday-pro-auto.vercel.app

paths:
  /api/weekday:
    get:
      operationId: getWeekday
      summary: ตรวจสอบวันจริงจากวันที่ (รองรับ timezone)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "10/09/2568"
          description: วันที่รูปแบบ DD/MM/YYYY (พ.ศ. หรือ ค.ศ.)
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
          description: timezone ของพื้นที่ เช่น Asia/Bangkok, America/New_York
      responses:
        "200":
          description: Successful Response

  /api/weekday-th:
    get:
      operationId: getWeekdayThai
      summary: แปลงวันที่ไทยและแสดงวันจริง (รองรับ timezone)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "10/09/2568"
        - name: style
          in: query
          required: false
          schema:
            type: string
            enum: ["short", "long"]
            default: "short"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
          description: timezone ของพื้นที่ (ค่าเริ่มต้นคือ Asia/Bangkok)
      responses:
        "200":
          description: Successful Response

  /api/astro-weekday:
    get:
      operationId: getAstroWeekday
      summary: ตรวจสอบวันจริง + เวลา + timezone + สถานที่เกิด
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time
          in: query
          required: false
          schema:
            type: string
            example: "11:00"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
        - name: place
          in: query
          required: false
          schema:
            type: string
            example: "Bangkok"
      responses:
        "200":
          description: Successful Response

  /api/astro-chart:
    get:
      operationId: getAstroChart
      summary: คำนวณพื้นดวง (เลือก sidereal/tropical อัตโนมัติ)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time
          in: query
          required: true
          schema:
            type: string
            example: "11:00"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
        - name: lat
          in: query
          required: false
          schema:
            type: number
            example: 13.75
        - name: lon
          in: query
          required: false
          schema:
            type: number
            example: 100.5
      responses:
        "200":
          description: Successful Response

  /api/astro-transit:
    get:
      operationId: getAstroTransit
      summary: วิเคราะห์ดาวจรเทียบพื้นดวง
      parameters:
        - name: base_date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: base_time
          in: query
          required: false
          schema:
            type: string
            example: "12:00"
        - name: target_date
          in: query
          required: false
          schema:
            type: string
            example: "08/05/2569"
        - name: lat
          in: query
          required: false
          schema:
            type: number
            example: 13.75
        - name: lon
          in: query
          required: false
          schema:
            type: number
            example: 100.5
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response

  /api/astro-match:
    get:
      operationId: getAstroMatch
      summary: วิเคราะห์ดวงคู่ (ความสัมพันธ์)
      parameters:
        - name: date1
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time1
          in: query
          required: true
          schema:
            type: string
            example: "11:00"
        - name: lat1
          in: query
          required: true
          schema:
            type: number
            example: 13.75
        - name: lon1
          in: query
          required: true
          schema:
            type: number
            example: 100.5
        - name: date2
          in: query
          required: true
          schema:
            type: string
            example: "08/06/2514"
        - name: time2
          in: query
          required: true
          schema:
            type: string
            example: "23:56"
        - name: lat2
          in: query
          required: true
          schema:
            type: number
            example: 18.79
        - name: lon2
          in: query
          required: true
          schema:
            type: number
            example: 98.98
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
      responses:
        "200":
          description: Successful Response
